OmniAuth.config.test_mode = true

OmniAuth.config.mock_auth[:google_oauth2] = OmniAuth::AuthHash.new(OmniAuth::AuthHash.new({
  "provider"=>"google_oauth2",
  "uid"=>"10304324527584231",
  "info"=>
   {"name"=>"ホゲ太郎",
    "email"=>"hoge.fuga@bar.co.jp",
    "unverified_email"=>"hoge.fuga@bar.co.jp",
    "email_verified"=>true,
    "first_name"=>"太郎",
    "last_name"=>"ホゲ",
    "image"=>"https://lh3.googleusercontent.com/-M_QnK8__qMU/AAdwndfndAI/AxxXXXXXXXXXXXXX/AMZuuckA3FYeHLDAmc-EF6-GGSdawdaaghA/photo.jpg"},
  "credentials"=>
   {"token"=>
     "yafaesfafagaragargapkg;aoaroigjaiiiiiioiagiagjeoKR6_U",
    "refresh_token"=>"kpotshkoirhjasiougaalvnaiufefwadmsRl8",
    "expires_at"=>15601249,
    "expires"=>true},
  "extra"=>
   {"id_token"=>
     "eyJhbGcijogriaogaohvaniuahfeuiiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY2dwad91bnRzLmdvb2dsZS5jb20iLCJhenAiOiIzNDIwNDM0ODU0ODMtMDAwOGI5cWJpN2lyZTBuaTJ1ZjJkcWVyZ2k2dWYxdjEuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiIzNDIwNDM0ODU0ODMtMDAwOGI5cWJpN2lyZTBuaTJ1ZjJkcWVyZ2k2dWYxdjEuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMDMwOTcxNjcwMDUzMjc1ODY4NDkiLCJoZCI6ImRpLXYuY28uanAiLCJlbWFpbCI6Inl1a2kudW5vQGRpLXYuY28uanAiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXRfaGFzaCI6IngxVzRJbXZoMVlFT1YwNEJxSV9uUHciLCJuYW1lIjoi6bWc6YeO5L2R57SAIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS8tTV9Rbks4X19xTVUvQUFBQUFBQUFBQUkvQUFBQUFBQUFBQUEvQU1adXVja0EzRlllSExEQW1jLUVGNi1HR1NIZjdFaEtZQS9zOTYtYy9waG90by5qcGciLCJnaXZlbl9uYW1lIjoi5L2R57SAIiwiZmFtaWx5X25hbWUiOiLptZzph44iLCJsb2NhbGUiOiJqYSIsImlhdCI6MTU5NjY5OTQ5OSwiZXhwIjoxNTk2NzAzMDk5fQ.SpsecBa0PxGYZiakrAw_JYxI_EV14QDA1Pjxd-4AWo0DZ_d42hvgQPHlhvPyHEIW3z7TsO7akVpy8XffTWY0aEp1OkRGlLjv5keLZrRNAk-JLJUY9p8hkNGNNC0TWZIOVJqffV8WjTjiwqY6y9-lN-AeovzW5plWlf4Mba0044spiLz6lbjqHzcsJeA2wf7hnQn6klnvxbtHeb2RpkBTXrMGKlMp9XgyI9gujM6802ioYcy8V50poVcMWK6wDAkvIy2c8O0mxqHoF7_a1oP-FSxrkuYX314qWCTwKQSJTzqKqHbnNePxdqOy8-iiwXVdeyYIx7wtDfDKke0sEzKUNw",
    "id_info"=>
     {"iss"=>"https://accounts.google.com",
      "azp"=>"7453485483-0008dawggrwabadbadhraefgi6uf1v1.apps.googleusercontent.com",
      "aud"=>"7453485483-0008dawggrwabadbadhraefgi6uf1v1.apps.googleusercontent.com",
      "sub"=>"7654862344586849",
      "hd"=>"bar.co.jp",
      "email"=>"hoge.fuga@bar.co.jp",
      "email_verified"=>true,
      "at_hash"=>"x463225ihddBqI_nPw",
      "name"=>"ホゲ太郎",
      "picture"=>"https://lh3.googleusercontent.com/-M_QnK8__qMU/AAdwndfndAI/AxxXXXXXXXXXXXXX/AMZuuckA3FYeHLDAmc-EF6-GGSdawdaaghA/photo.jpg",
      "given_name"=>"太郎",
      "family_name"=>"ホゲ",
      "locale"=>"ja",
      "iat"=>15966432324,
      "exp"=>1239672199},
    "raw_info"=>
     {"sub"=>"10906304286849",
      "name"=>"ホゲ太郎",
      "given_name"=>"ホゲ",
      "family_name"=>"太郎",
      "picture"=>"https://lh3.googleusercontent.com/-M_QnK8__qMU/AAdwndfndAI/AxxXXXXXXXXXXXXX/AMZuuckA3FYeHLDAmc-EF6-GGSdawdaaghA/photo.jpg",
      "email"=>"hoge.fuga@bar.co.jp",
      "email_verified"=>true,
      "locale"=>"ja",
      "hd"=>"bar.co.jp"
     }
   }
 }))
